---
layout: cv
title: Aaron Harrison's CV
---
# Aaron Harrison
Data Scientist, Organizational Network Scientist, Adjunct Professor

<div id="webaddress">
| <a href="https://www.linkedin.com/in/aaron-harrison/">My LinkedIn page</a>
</div>


## Currently

Lorem ipsum

### Specialized in




### Research interests




## Education

`2004-2011`
__Brigham Young University__ Chemical Engineering, B.S.

`2011-2015`
__Purdue University__ Chemical Engineering, PhD



## Publications


### Patents

`2021`
System for offline processing of organizational networks, US 10992776 · Issued Apr 1, 2021

`2020`
Engineered Polymer Detection Swab, US 10794796 · Issued Oct 6, 2020


## Occupation


`2024`
__Adjunct Professor of Data Science__, Brigham Young University - Idaho

- Introducing students to the power (and practicality) of Python in all things Data Science

`2023`
__Workforce Analytics Specialist__, Idaho National Laboratory

- Creating data-driven solutions through people analytics to help secure our energy future by enabling today's scientists, engineers, technicians, and other professionals to do their best, collaborative work. 

`2022`
__Sr. Data and Applied Scientist__, Microsoft

- Developed the newest tools for Microsoft Viva.

`2017`
__Data and Applied Scientist__, Microsoft

- Designed tools for Fortune 500 companies that extract insights from their own big data to help them improve collaboration behaviors that lead to more innovation.

`2016`
__Postdoctoral Researcher__, Los Alamos National Laboratory

- Designed an experimental, lab-scale flow battery for concentrated solar power applications



<!-- ### Footer

Last updated: July 2024 -->